# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170)),
                ('ip_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VmDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerState', models.CharField(max_length=10, null=True)),
                ('maxCpuUsage', models.CharField(max_length=20, null=True)),
                ('maxMemoryUsage', models.CharField(max_length=20, null=True)),
                ('template', models.CharField(max_length=10, null=True)),
                ('memorySizeMB', models.IntegerField(null=True)),
                ('numCpu', models.IntegerField(null=True)),
                ('numEthernetCards', models.IntegerField(null=True)),
                ('numVirtualDisks', models.IntegerField(null=True)),
                ('instanceUuid', models.CharField(max_length=100, null=True)),
                ('uuid', models.CharField(max_length=100, null=True)),
                ('committed', models.IntegerField(null=True)),
                ('uncommitted', models.IntegerField(null=True)),
                ('overallCpuUsage', models.IntegerField(null=True)),
                ('overallCpuDemand', models.IntegerField(null=True)),
                ('guestMemoryUsage', models.IntegerField(null=True)),
                ('hostMemoryUsage', models.IntegerField(null=True)),
                ('guestHeartbeatStatus', models.CharField(max_length=100, null=True)),
                ('privateMemory', models.IntegerField(null=True)),
                ('consumedOverheadMemory', models.CharField(max_length=100, null=True)),
                ('ftLatencyStatus', models.CharField(max_length=100, null=True)),
                ('host_ip', models.CharField(max_length=100, null=True)),
                ('vcenter_date', models.DateField()),
                ('createdate', models.DateField()),
                ('id_vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Vm')),
            ],
        ),
    ]
