# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmdetails',
            name='instanceUuid',
        ),
        migrations.AddField(
            model_name='vm',
            name='uuid',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='ip_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='name',
            field=models.CharField(max_length=170, null=True),
        ),
    ]
