# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_auto_20160810_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdetails',
            name='createdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vmdetails',
            name='vcenter_date',
            field=models.DateField(null=True),
        ),
    ]
