# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0004_auto_20160810_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vmdetails',
            old_name='id_vm',
            new_name='vm',
        ),
    ]
