# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0006_auto_20160810_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdetails',
            name='guestmemoryusage',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vmdetails',
            name='hostmemoryusage',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vmdetails',
            name='privatememory',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
