# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0008_auto_20160810_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmdetails',
            name='uncommitted',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
