# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('ip', models.CharField(max_length=30, null=True)),
                ('uuid', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofvms', models.CharField(max_length=100, null=True)),
                ('numberofdatastores', models.IntegerField(null=True)),
                ('memorySize', models.IntegerField(null=True)),
                ('numCpuCores', models.IntegerField(null=True)),
                ('numNics', models.IntegerField(null=True)),
                ('cpuModel', models.CharField(max_length=100, null=True)),
                ('cpuMhz', models.CharField(max_length=100, null=True)),
                ('numCpuPkgs', models.IntegerField(null=True)),
                ('numHBAs', models.IntegerField(null=True)),
                ('overallStatus', models.CharField(max_length=100, null=True)),
                ('port', models.CharField(max_length=100, null=True)),
                ('vmotionEnabled', models.CharField(max_length=100, null=True)),
                ('uptime', models.CharField(max_length=100, null=True)),
                ('overallMemoryUsage', models.CharField(max_length=100, null=True)),
                ('overallCpuUsage', models.CharField(max_length=100, null=True)),
                ('bootTime', models.CharField(max_length=100, null=True)),
                ('connectionState', models.CharField(max_length=100, null=True)),
                ('dasHostState', models.CharField(max_length=100, null=True)),
                ('hostMaxVirtualDiskCapacity', models.CharField(max_length=100, null=True)),
                ('maxEVCModeKey', models.CharField(max_length=100, null=True)),
                ('managementServerIp', models.CharField(max_length=100, null=True)),
                ('currentEVCModeKey', models.CharField(max_length=100, null=True)),
                ('customValue', models.CharField(max_length=100, null=True)),
                ('vcenterdate', models.DateField()),
                ('createdate', models.DateField()),
                ('id_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.Host')),
            ],
        ),
    ]
