# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_auto_20160810_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdetails',
            old_name='id_host',
            new_name='host',
        ),
    ]
