# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20160810_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdetails',
            old_name='bootTime',
            new_name='boottime',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='connectionState',
            new_name='connectionstate',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='cpuMhz',
            new_name='cpumhz',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='cpuModel',
            new_name='cpumodel',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='currentEVCModeKey',
            new_name='currentevcmodeKey',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='customValue',
            new_name='customvalue',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='dasHostState',
            new_name='dashoststate',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='hostMaxVirtualDiskCapacity',
            new_name='hostmaxvirtualdiskcapacity',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='managementServerIp',
            new_name='managementserverip',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='maxEVCModeKey',
            new_name='maxevcmodekey',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='numCpuCores',
            new_name='numcpucores',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='numCpuPkgs',
            new_name='numcpupkgs',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='numHBAs',
            new_name='numhbas',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='numNics',
            new_name='numnics',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='overallCpuUsage',
            new_name='overallcpuusage',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='overallMemoryUsage',
            new_name='overallmemoryusage',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='overallStatus',
            new_name='overallstatus',
        ),
        migrations.RenameField(
            model_name='hostdetails',
            old_name='vmotionEnabled',
            new_name='vmotionenabled',
        ),
    ]
