# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_auto_20160810_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostdetails',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
