# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_hostdetails_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdetails',
            old_name='memorySize',
            new_name='memorysize',
        ),
    ]
