# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_auto_20160810_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostdetails',
            old_name='currentevcmodeKey',
            new_name='currentevcmodekey',
        ),
    ]
