# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_auto_20160810_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdetails',
            name='memorysize',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
